name = "Perkeo Observatory"
description = "Perkeo with the Telescope and Observatory Vouchers."
author = "tacodiva"
dateCreated = "2025-01-01T05:46:12.6691000Z"

[[must]]
type = "Voucher"
value = "Telescope"
antes = [1, 2, 3]

[[must]]
type = "Voucher"
value = "Observatory"
antes = [1, 2, 3]

[[must]]
type = "souljoker"
edition = "Negative"
value = "Perkeo"
antes = [1]

[[should]]
type = "souljoker"
value = "Perkeo"
antes = [1]

[[should]]
type = "souljoker"
value = "Perkeo"
antes = [2]

[[should]]
type = "souljoker"
value = "Perkeo"
antes = [3]

[[should]]
type = "Joker"
value = "Blueprint"
antes = [1]

[should.sources]
packSlots = [0]
